### ISSUE TITLE
Ошибка SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by paulbraam** [vault-developer/telegram-quiz-bot#1]
Добрый день!

Я получаю следующую ошибку, когда запускаю npm start:

```
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\users\home\desktop\telegram-quiz-bot\src\index.js:1:77)

npm ERR! Windows_NT 10.0.18362
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! telegram-quiz-bot@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telegram-quiz-bot@1.0.0 start script 'node src/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the telegram-quiz-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs telegram-quiz-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls telegram-quiz-bot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\users\home\desktop\telegram-quiz-bot\npm-debug.log

```

Подскажите, как можно поправить
Благодарю заранее

**Comment by vault-developer** [comment]
Решили вопрос, необходимо было обновить node до 10ой версии
